-- Department master data schema
CREATE TABLE IF NOT EXISTS `department` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_code` VARCHAR(50) NOT NULL,
  `department_code` VARCHAR(50) NOT NULL,
  `department_id` VARCHAR(100) NOT NULL,
  `department_name` VARCHAR(150) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_department_code` (`department_code`),
  UNIQUE KEY `uniq_department_id` (`department_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Seed departments based on provided mappings
INSERT INTO `department` (`company_code`, `department_code`, `department_id`, `department_name`) VALUES
('TLCI','TLCI-IT','10','IT'),
('TLCI','TLCI-FIN','20','FIN'),
('TLCI','TLCI-ACC','30','ACC'),
('TLCI','TLCI-LOG','40','LOG'),
('TLCI','TLCI-PR','50','PR'),
('TLCI','TLCI-SALES','60','SALES'),
('TLCI','TLCI-ENGR','70','ENGR'),
('MPAV','MPAV-IT','11','IT'),
('MPAV','MPAV-FIN','21','FIN'),
('MPAV','MPAV-ACC','31','ACC'),
('MPAV','MPAV-LOG','41','LOG'),
('MPAV','MPAV-PR','51','PR'),
('MPAV','MPAV-SALES','61','SALES'),
('MPAV','MPAV-ENGR','71','ENGR'),
('MPFF','MPFF-IT','12','IT'),
('MPFF','MPFF-FIN','22','FIN'),
('MPFF','MPFF-ACC','32','ACC'),
('MPFF','MPFF-LOG','42','LOG'),
('MPFF','MPFF-PR','52','PR'),
('MPFF','MPFF-SALES','62','SALES'),
('MPFF','MPFF-ENGR','72','ENGR'),
('MPDF','MPDF-IT','13','IT'),
('MPDF','MPDF-FIN','23','FIN'),
('MPDF','MPDF-ACC','33','ACC'),
('MPDF','MPDF-LOG','43','LOG'),
('MPDF','MPDF-PR','53','PR'),
('MPDF','MPDF-SALES','63','SALES'),
('MPDF','MPDF-ENGR','73','ENGR'),
('UHDFI','UHDFI-IT','14','IT'),
('UHDFI','UHDFI-FIN','24','FIN'),
('UHDFI','UHDFI-ACC','34','ACC'),
('UHDFI','UHDFI-LOG','44','LOG'),
('UHDFI','UHDFI-PR','54','PR'),
('UHDFI','UHDFI-SALES','64','SALES'),
('UHDFI','UHDFI-ENGR','74','ENGR'),
('MPNAT','MPNAT-IT','15','IT'),
('MPNAT','MPNAT-FIN','25','FIN'),
('MPNAT','MPNAT-ACC','35','ACC'),
('MPNAT','MPNAT-LOG','45','LOG'),
('MPNAT','MPNAT-PR','55','PR'),
('MPNAT','MPNAT-SALES','65','SALES'),
('MPNAT','MPNAT-ENGR','75','ENGR');